2025-03-02 22:01:35,982 - INFO - Запуск приложения и инициализация базы данных...
2025-03-02 22:01:35,982 - DEBUG - Начало инициализации базы данных...
2025-03-02 22:01:36,051 - INFO - База данных успешно инициализирована.
2025-03-02 22:01:36,051 - INFO - Приложение успешно запущено. Соединение с базой данных установлено.
2025-03-02 22:01:36,051 - INFO - Директория уже существует: ./video_temp
2025-03-02 22:01:36,052 - INFO - Директория уже существует: ./image_temp
2025-03-02 22:01:36,052 - INFO - Директория уже существует: ./output_video
2025-03-02 22:01:36,052 - INFO - Директория уже существует: ./output_preview
2025-03-02 22:01:36,052 - INFO - Директория уже существует: ./user_logo
2025-03-02 22:01:36,053 - INFO - Задача fetch_and_cache_profiles добавлена в расписание (каждые 5 минут).
2025-03-02 22:01:36,053 - INFO - Задача sync_data_to_db добавлена в расписание (каждые 8 минут).
2025-03-02 22:01:36,053 - INFO - Задача очистки временных файлов добавлена в расписание (каждый день в 00:00).
2025-03-02 22:01:36,053 - INFO - Задача очистки логов добавлена в расписание (каждые 5 минут).
2025-03-02 22:01:36,053 - INFO - Планировщик задач успешно запущен.
2025-03-02 22:01:36,068 - INFO - Запуск подписки на канал Redis для получения задач
2025-03-02 22:01:36,077 - INFO - Redis доступен.
2025-03-02 22:01:36,077 - INFO - Подключаемся к Redis...
2025-03-02 22:01:36,077 - INFO - Подписались на канал video_tasks
2025-03-02 22:02:06,172 - INFO - Открытие сессии с БД...
2025-03-02 22:02:06,174 - INFO - Сессия с БД успешно открыта.
2025-03-02 22:02:06,186 - INFO - Начало хеширования номера кошелька.
2025-03-02 22:02:06,186 - INFO - Хеш номера кошелька: 4d79e8e3826af75078b2aed75763bb93e405751d0e6c20aa2f1ff85b2f034dbc
2025-03-02 22:02:06,186 - INFO - Поиск пользователя в базе данных.
2025-03-02 22:02:06,233 - INFO - Пользователь найден с ID 935
2025-03-02 22:02:06,313 - INFO - Попытка получить избранное из кэша Redis.
2025-03-02 22:02:06,316 - INFO - Нет избранных профилей в кэше для пользователя 935.
2025-03-02 22:02:06,316 - INFO - Избранное не найдено в кэше. Загружаем из базы данных.
2025-03-02 22:02:06,318 - INFO - Избранное загружено из БД: []
2025-03-02 22:02:06,318 - INFO - Генерация токенов для пользователя.
2025-03-02 22:02:06,319 - INFO - Токены успешно сгенерированы.
2025-03-02 22:02:06,319 - INFO - Закрытие сессии с БД.
2025-03-02 22:02:29,980 - INFO - Получен запрос на загрузку изображения от пользователя с ID: 935
2025-03-02 22:02:29,995 - INFO - Изображение сохранено во временной директории: ./image_temp/63462d88-18e5-43fd-82ae-399b0c212b73_orig_cat.webp (Размер: 0.07 MB)
2025-03-02 22:02:29,995 - INFO - Изображение успешно загружено: ./image_temp/63462d88-18e5-43fd-82ae-399b0c212b73_orig_cat.webp
2025-03-02 22:04:45,936 - INFO - Открытие сессии с БД...
2025-03-02 22:04:45,939 - INFO - Сессия с БД успешно открыта.
2025-03-02 22:04:45,942 - INFO - Начало хеширования номера кошелька.
2025-03-02 22:04:45,943 - INFO - Хеш номера кошелька: 4d79e8e3826af75078b2aed75763bb93e405751d0e6c20aa2f1ff85b2f034dbc
2025-03-02 22:04:45,943 - INFO - Поиск пользователя в базе данных.
2025-03-02 22:04:45,975 - INFO - Пользователь найден с ID 935
2025-03-02 22:04:45,979 - INFO - Попытка получить избранное из кэша Redis.
2025-03-02 22:04:45,982 - INFO - Нет избранных профилей в кэше для пользователя 935.
2025-03-02 22:04:45,982 - INFO - Избранное не найдено в кэше. Загружаем из базы данных.
2025-03-02 22:04:45,984 - INFO - Избранное загружено из БД: []
2025-03-02 22:04:45,984 - INFO - Генерация токенов для пользователя.
2025-03-02 22:04:45,985 - INFO - Токены успешно сгенерированы.
2025-03-02 22:04:45,986 - INFO - Закрытие сессии с БД.
2025-03-02 22:05:06,851 - INFO - Получен запрос на загрузку изображения от пользователя с ID: 935
2025-03-02 22:05:06,863 - INFO - Изображение сохранено во временной директории: ./image_temp/e3c4b64f-59ed-4b53-953b-ec60fc0bd75c_orig_cat.webp (Размер: 0.07 MB)
2025-03-02 22:05:06,863 - INFO - Изображение успешно загружено: ./image_temp/e3c4b64f-59ed-4b53-953b-ec60fc0bd75c_orig_cat.webp
2025-03-02 22:05:31,019 - INFO - Получены данные профиля: {'name': 'Ебало Говяжее', 'website_or_social': 'https://twitter.com/johndoe', 'activity_hobbies': 'Gaming, Traveling', 'hashtags': ['Долбиться в ротан'], 'adress': ['123 Example Street, Example City', '456 Another Street, Another City'], 'city': 'Поппенгагген', 'coordinates': [(55.77, 37.68)], 'is_in_mlm': 1, 'is_incognito': False, 'wallet_number': '0x35b9B8cfa39fA73f48Ad574F630D86EBC2d4753', 'language': None}
2025-03-02 22:05:31,020 - INFO - Получены данные о изображении: {'image_path': './image_temp/e3c4b64f-59ed-4b53-953b-ec60fc0bd75c_orig_cat.webp'}
2025-03-02 22:05:31,040 - INFO - Путь к изображению: ./image_temp/e3c4b64f-59ed-4b53-953b-ec60fc0bd75c_orig_cat.webp
2025-03-02 22:05:31,040 - INFO - Абсолютный путь к изображению: /app/image_temp/e3c4b64f-59ed-4b53-953b-ec60fc0bd75c_orig_cat.webp
2025-03-02 22:05:31,045 - INFO - Изображение перемещено в директорию user_logo: ./user_logo/587354f8-0db6-42de-bcf0-78671e6450e3_e3c4b64f-59ed-4b53-953b-ec60fc0bd75c_orig_cat.webp (Размер: 0.07 MB)
2025-03-02 22:05:31,045 - INFO - Путь к файлу для сохранения в БД: ./user_logo/587354f8-0db6-42de-bcf0-78671e6450e3_e3c4b64f-59ed-4b53-953b-ec60fc0bd75c_orig_cat.webp
2025-03-02 22:05:31,045 - INFO - Изображение успешно перемещено в постоянную папку: ./user_logo/587354f8-0db6-42de-bcf0-78671e6450e3_e3c4b64f-59ed-4b53-953b-ec60fc0bd75c_orig_cat.webp
2025-03-02 22:05:31,046 - INFO - Открытие сессии с БД...
2025-03-02 22:05:31,046 - INFO - Сессия с БД успешно открыта.
2025-03-02 22:05:31,063 - ERROR - Непредвиденная ошибка: 'FormData' object is not subscriptable
2025-03-02 22:05:31,066 - ERROR - Ошибка в контексте сессии: 500: Непредвиденная ошибка. Попробуйте позже.
2025-03-02 22:05:31,066 - INFO - Закрытие сессии с БД.
2025-03-02 22:05:31,066 - ERROR - Ошибка в функции save_profile_to_db_without_video: 500: Непредвиденная ошибка. Попробуйте позже.
2025-03-02 22:05:31,066 - ERROR - Ошибка в эндпоинте /save_profile_without_video/: 500: Непредвиденная ошибка. Попробуйте позже.
2025-03-02 22:06:36,059 - INFO - Открытие сессии с БД...
2025-03-02 22:06:36,063 - INFO - Сессия с БД успешно открыта.
2025-03-02 22:06:36,140 - INFO - Логи старше 10 минут и строки с неправильным форматом удалены из файла video_service.log.
2025-03-02 22:06:36,591 - INFO - Успешно обработано и закэшировано 908 профилей в Redis.
2025-03-02 22:06:36,591 - INFO - Закрытие сессии с БД.
2025-03-02 22:09:36,059 - INFO - Открытие сессии с БД...
2025-03-02 22:09:36,063 - INFO - Сессия с БД успешно открыта.
2025-03-02 22:09:36,123 - INFO - Закрытие сессии с БД.
2025-03-02 22:09:36,123 - INFO - Данные о избранном и счетчике подписчиков успешно синхронизированы из кеша в базу данных для всех пользователей.
2025-03-02 22:09:38,844 - ERROR - Ошибка при получении сообщения: Connection closed by server.
Module: __main__, Function: main, Line: 140
2025-03-02 22:09:38,858 - ERROR - Ошибка при получении сообщения: Error 111 connecting to redis:6379. Connect call failed ('172.19.0.3', 6379).
Module: __main__, Function: main, Line: 140
2025-03-02 22:09:38,860 - ERROR - Ошибка при получении сообщения: Error 111 connecting to redis:6379. Connect call failed ('172.19.0.3', 6379).
Module: __main__, Function: main, Line: 140
2025-03-02 22:09:38,860 - ERROR - Ошибка при получении сообщения: Error 111 connecting to redis:6379. Connect call failed ('172.19.0.3', 6379).
Module: __main__, Function: main, Line: 140
2025-03-02 22:09:38,861 - ERROR - Ошибка при получении сообщения: Error 111 connecting to redis:6379. Connect call failed ('172.19.0.3', 6379).
Module: __main__, Function: main, Line: 140
2025-03-02 22:09:38,862 - ERROR - Ошибка при получении сообщения: Error 111 connecting to redis:6379. Connect call failed ('172.19.0.3', 6379).
Module: __main__, Function: main, Line: 140
2025-03-02 22:09:38,862 - ERROR - Ошибка при получении сообщения: Error 111 connecting to redis:6379. Connect call failed ('172.19.0.3', 6379).
Module: __main__, Function: main, Line: 140
2025-03-02 22:09:38,863 - ERROR - Ошибка при получении сообщения: Error 111 connecting to redis:6379. Connect call failed ('172.19.0.3', 6379).
Module: __main__, Function: main, Line: 140
2025-03-02 22:09:38,864 - ERROR - Ошибка при получении сообщения: Error 111 connecting to redis:6379. Connect call failed ('172.19.0.3', 6379).
Module: __main__, Function: main, Line: 140
2025-03-02 22:09:38,864 - ERROR - Ошибка при получении сообщения: Error 111 connecting to redis:6379. Connect call failed ('172.19.0.3', 6379).
Module: __main__, Function: main, Line: 140
2025-03-02 22:09:38,866 - ERROR - Ошибка при получении сообщения: Error 111 connecting to redis:6379. Connect call failed ('172.19.0.3', 6379).
Module: __main__, Function: main, Line: 140
2025-03-02 22:12:56,944 - INFO - Запуск подписки на канал Redis для получения задач
2025-03-02 22:12:56,955 - INFO - Redis доступен.
2025-03-02 22:12:56,955 - INFO - Подключаемся к Redis...
2025-03-02 22:12:56,955 - INFO - Подписались на канал video_tasks
2025-03-02 22:12:56,969 - INFO - Запуск приложения и инициализация базы данных...
2025-03-02 22:12:56,970 - DEBUG - Начало инициализации базы данных...
2025-03-02 22:12:57,048 - INFO - База данных успешно инициализирована.
2025-03-02 22:12:57,048 - INFO - Приложение успешно запущено. Соединение с базой данных установлено.
2025-03-02 22:12:57,048 - INFO - Директория уже существует: ./video_temp
2025-03-02 22:12:57,048 - INFO - Директория уже существует: ./image_temp
2025-03-02 22:12:57,049 - INFO - Директория уже существует: ./output_video
2025-03-02 22:12:57,049 - INFO - Директория уже существует: ./output_preview
2025-03-02 22:12:57,049 - INFO - Директория уже существует: ./user_logo
2025-03-02 22:12:57,051 - INFO - Задача fetch_and_cache_profiles добавлена в расписание (каждые 5 минут).
2025-03-02 22:12:57,051 - INFO - Задача sync_data_to_db добавлена в расписание (каждые 8 минут).
2025-03-02 22:12:57,051 - INFO - Задача очистки временных файлов добавлена в расписание (каждый день в 00:00).
2025-03-02 22:12:57,052 - INFO - Задача очистки логов добавлена в расписание (каждые 5 минут).
2025-03-02 22:12:57,053 - INFO - Планировщик задач успешно запущен.
2025-03-02 22:13:31,695 - INFO - Открытие сессии с БД...
2025-03-02 22:13:31,697 - INFO - Сессия с БД успешно открыта.
2025-03-02 22:13:31,713 - INFO - Начало хеширования номера кошелька.
2025-03-02 22:13:31,716 - INFO - Хеш номера кошелька: 4d79e8e3826af75078b2aed75763bb93e405751d0e6c20aa2f1ff85b2f034dbc
2025-03-02 22:13:31,716 - INFO - Поиск пользователя в базе данных.
2025-03-02 22:13:31,759 - INFO - Пользователь найден с ID 935
2025-03-02 22:13:31,869 - INFO - Попытка получить избранное из кэша Redis.
2025-03-02 22:13:31,875 - INFO - Нет избранных профилей в кэше для пользователя 935.
2025-03-02 22:13:31,875 - INFO - Избранное не найдено в кэше. Загружаем из базы данных.
2025-03-02 22:13:31,882 - INFO - Избранное загружено из БД: []
2025-03-02 22:13:31,882 - INFO - Генерация токенов для пользователя.
2025-03-02 22:13:31,882 - INFO - Токены успешно сгенерированы.
2025-03-02 22:13:31,883 - INFO - Закрытие сессии с БД.
2025-03-02 22:13:52,677 - INFO - Получен запрос на загрузку изображения от пользователя с ID: 935
2025-03-02 22:13:52,694 - INFO - Изображение сохранено во временной директории: ./image_temp/d47aaaa6-f3c6-4c0d-aa04-0aa009a0e40c_orig_cat.webp (Размер: 0.07 MB)
2025-03-02 22:13:52,694 - INFO - Изображение успешно загружено: ./image_temp/d47aaaa6-f3c6-4c0d-aa04-0aa009a0e40c_orig_cat.webp
2025-03-02 22:14:52,863 - INFO - Получены данные профиля: {'name': 'Ебало Говяжее', 'website_or_social': 'https://twitter.com/johndoe', 'activity_hobbies': 'Gaming, Traveling', 'hashtags': ['Долбиться в ротан'], 'adress': ['123 Example Street, Example City', '456 Another Street, Another City'], 'city': 'Поппенгагген', 'coordinates': [(55.77, 37.68)], 'is_in_mlm': 1, 'is_incognito': False, 'wallet_number': '0x35b9B8cfa39fA73f48Ad574F630D86EBC2d4753', 'language': None}
2025-03-02 22:14:52,865 - INFO - Получены данные о изображении: {'image_path': './image_temp/d47aaaa6-f3c6-4c0d-aa04-0aa009a0e40c_orig_cat.webp'}
2025-03-02 22:14:52,877 - INFO - Путь к изображению: ./image_temp/d47aaaa6-f3c6-4c0d-aa04-0aa009a0e40c_orig_cat.webp
2025-03-02 22:14:52,877 - INFO - Абсолютный путь к изображению: /app/image_temp/d47aaaa6-f3c6-4c0d-aa04-0aa009a0e40c_orig_cat.webp
2025-03-02 22:14:52,885 - INFO - Изображение перемещено в директорию user_logo: ./user_logo/77392b9e-dc08-4598-ba57-b9c4bcb2d42b_d47aaaa6-f3c6-4c0d-aa04-0aa009a0e40c_orig_cat.webp (Размер: 0.07 MB)
2025-03-02 22:14:52,885 - INFO - Путь к файлу для сохранения в БД: ./user_logo/77392b9e-dc08-4598-ba57-b9c4bcb2d42b_d47aaaa6-f3c6-4c0d-aa04-0aa009a0e40c_orig_cat.webp
2025-03-02 22:14:52,885 - INFO - Изображение успешно перемещено в постоянную папку: ./user_logo/77392b9e-dc08-4598-ba57-b9c4bcb2d42b_d47aaaa6-f3c6-4c0d-aa04-0aa009a0e40c_orig_cat.webp
2025-03-02 22:14:52,886 - INFO - Открытие сессии с БД...
2025-03-02 22:14:52,886 - INFO - Сессия с БД успешно открыта.
2025-03-02 22:14:52,928 - INFO - Создан профиль для пользователя 935, флаг is_profile_created установлен в True
2025-03-02 22:14:52,933 - INFO - Хэштеги добавлены/обновлены для профиля пользователя 935
2025-03-02 22:14:52,945 - INFO - Профиль успешно сохранен.
2025-03-02 22:14:52,945 - INFO - Закрытие сессии с БД.
2025-03-02 22:17:14,218 - ERROR - Ошибка при получении сообщения: Connection closed by server.
Module: __main__, Function: main, Line: 140
2025-03-02 22:17:14,235 - ERROR - Ошибка при получении сообщения: Error 111 connecting to redis:6379. Connect call failed ('172.19.0.3', 6379).
Module: __main__, Function: main, Line: 140
2025-03-02 22:17:14,236 - ERROR - Ошибка при получении сообщения: Error 111 connecting to redis:6379. Connect call failed ('172.19.0.3', 6379).
Module: __main__, Function: main, Line: 140
2025-03-02 22:17:14,237 - ERROR - Ошибка при получении сообщения: Error 111 connecting to redis:6379. Connect call failed ('172.19.0.3', 6379).
Module: __main__, Function: main, Line: 140
2025-03-02 22:17:14,239 - ERROR - Ошибка при получении сообщения: Error 111 connecting to redis:6379. Connect call failed ('172.19.0.3', 6379).
Module: __main__, Function: main, Line: 140
2025-03-02 22:17:14,240 - ERROR - Ошибка при получении сообщения: Error 111 connecting to redis:6379. Connect call failed ('172.19.0.3', 6379).
Module: __main__, Function: main, Line: 140
2025-03-02 22:17:14,241 - ERROR - Ошибка при получении сообщения: Error 111 connecting to redis:6379. Connect call failed ('172.19.0.3', 6379).
Module: __main__, Function: main, Line: 140
2025-03-02 22:17:14,243 - ERROR - Ошибка при получении сообщения: Error 111 connecting to redis:6379. Connect call failed ('172.19.0.3', 6379).
Module: __main__, Function: main, Line: 140
2025-03-02 22:17:14,244 - ERROR - Ошибка при получении сообщения: Error 111 connecting to redis:6379. Connect call failed ('172.19.0.3', 6379).
Module: __main__, Function: main, Line: 140
2025-03-02 22:17:14,245 - ERROR - Ошибка при получении сообщения: Error 111 connecting to redis:6379. Connect call failed ('172.19.0.3', 6379).
Module: __main__, Function: main, Line: 140
2025-03-02 22:17:14,246 - ERROR - Ошибка при получении сообщения: Error 111 connecting to redis:6379. Connect call failed ('172.19.0.3', 6379).
Module: __main__, Function: main, Line: 140
2025-03-02 22:17:14,247 - ERROR - Ошибка при получении сообщения: Error 111 connecting to redis:6379. Connect call failed ('172.19.0.3', 6379).
Module: __main__, Function: main, Line: 140
2025-03-02 22:17:14,249 - ERROR - Ошибка при получении сообщения: Error 111 connecting to redis:6379. Connect call failed ('172.19.0.3', 6379).
Module: __main__, Function: main, Line: 140
2025-03-02 22:17:14,250 - ERROR - Ошибка при получении сообщения: Error 111 connecting to redis:6379. Connect call failed ('172.19.0.3', 6379).
Module: __main__, Function: main, Line: 140
2025-03-02 22:17:14,251 - ERROR - Ошибка при получении сообщения: Error 111 connecting to redis:6379. Connect call failed ('172.19.0.3', 6379).
Module: __main__, Function: main, Line: 140
2025-03-02 22:17:14,252 - ERROR - Ошибка при получении сообщения: Error 111 connecting to redis:6379. Connect call failed ('172.19.0.3', 6379).
Module: __main__, Function: main, Line: 140
2025-03-02 22:17:14,253 - ERROR - Ошибка при получении сообщения: Error 111 connecting to redis:6379. Connect call failed ('172.19.0.3', 6379).
Module: __main__, Function: main, Line: 140
2025-03-02 22:17:14,258 - ERROR - Ошибка при получении сообщения: Error 111 connecting to redis:6379. Connect call failed ('172.19.0.3', 6379).
Module: __main__, Function: main, Line: 140
2025-03-02 22:17:14,261 - ERROR - Ошибка при получении сообщения: Error 111 connecting to redis:6379. Connect call failed ('172.19.0.3', 6379).
Module: __main__, Function: main, Line: 140
2025-03-02 22:17:14,261 - ERROR - Ошибка при получении сообщения: Error 111 connecting to redis:6379. Connect call failed ('172.19.0.3', 6379).
Module: __main__, Function: main, Line: 140
2025-03-02 22:17:14,263 - ERROR - Ошибка при получении сообщения: Error 111 connecting to redis:6379. Connect call failed ('172.19.0.3', 6379).
Module: __main__, Function: main, Line: 140
2025-03-02 22:17:14,264 - ERROR - Ошибка при получении сообщения: Error 111 connecting to redis:6379. Connect call failed ('172.19.0.3', 6379).
Module: __main__, Function: main, Line: 140
2025-03-02 22:17:14,266 - ERROR - Ошибка при получении сообщения: Error 111 connecting to redis:6379. Connect call failed ('172.19.0.3', 6379).
Module: __main__, Function: main, Line: 140
2025-03-02 22:17:14,267 - ERROR - Ошибка при получении сообщения: Error 111 connecting to redis:6379. Connect call failed ('172.19.0.3', 6379).
Module: __main__, Function: main, Line: 140
2025-03-02 22:17:14,268 - ERROR - Ошибка при получении сообщения: Error 111 connecting to redis:6379. Connect call failed ('172.19.0.3', 6379).
Module: __main__, Function: main, Line: 140
2025-03-02 22:17:14,269 - ERROR - Ошибка при получении сообщения: Error 111 connecting to redis:6379. Connect call failed ('172.19.0.3', 6379).
Module: __main__, Function: main, Line: 140
2025-03-02 22:17:14,270 - ERROR - Ошибка при получении сообщения: Error 111 connecting to redis:6379. Connect call failed ('172.19.0.3', 6379).
Module: __main__, Function: main, Line: 140
2025-03-02 22:17:14,271 - ERROR - Ошибка при получении сообщения: Error 111 connecting to redis:6379. Connect call failed ('172.19.0.3', 6379).
Module: __main__, Function: main, Line: 140
2025-03-02 22:17:14,274 - ERROR - Ошибка при получении сообщения: Error 111 connecting to redis:6379. Connect call failed ('172.19.0.3', 6379).
Module: __main__, Function: main, Line: 140
2025-03-02 22:17:14,275 - ERROR - Ошибка при получении сообщения: Error 111 connecting to redis:6379. Connect call failed ('172.19.0.3', 6379).
Module: __main__, Function: main, Line: 140
2025-03-02 22:17:14,275 - ERROR - Ошибка при получении сообщения: Error 111 connecting to redis:6379. Connect call failed ('172.19.0.3', 6379).
Module: __main__, Function: main, Line: 140
2025-03-02 22:17:14,276 - ERROR - Ошибка при получении сообщения: Error 111 connecting to redis:6379. Connect call failed ('172.19.0.3', 6379).
Module: __main__, Function: main, Line: 140
2025-03-02 22:17:14,277 - ERROR - Ошибка при получении сообщения: Error 111 connecting to redis:6379. Connect call failed ('172.19.0.3', 6379).
Module: __main__, Function: main, Line: 140
2025-03-02 22:17:14,278 - ERROR - Ошибка при получении сообщения: Error 111 connecting to redis:6379. Connect call failed ('172.19.0.3', 6379).
Module: __main__, Function: main, Line: 140
2025-03-02 22:17:14,279 - ERROR - Ошибка при получении сообщения: Error 111 connecting to redis:6379. Connect call failed ('172.19.0.3', 6379).
Module: __main__, Function: main, Line: 140
2025-03-02 22:17:14,280 - ERROR - Ошибка при получении сообщения: Error 111 connecting to redis:6379. Connect call failed ('172.19.0.3', 6379).
Module: __main__, Function: main, Line: 140
2025-03-02 22:17:14,280 - ERROR - Ошибка при получении сообщения: Error 111 connecting to redis:6379. Connect call failed ('172.19.0.3', 6379).
Module: __main__, Function: main, Line: 140
2025-03-02 22:22:37,493 - INFO - Запуск подписки на канал Redis для получения задач
2025-03-02 22:22:37,713 - INFO - Запуск приложения и инициализация базы данных...
2025-03-02 22:22:37,713 - DEBUG - Начало инициализации базы данных...
2025-03-02 22:22:37,852 - INFO - База данных успешно инициализирована.
2025-03-02 22:22:37,852 - INFO - Приложение успешно запущено. Соединение с базой данных установлено.
2025-03-02 22:22:37,853 - INFO - Директория уже существует: ./video_temp
2025-03-02 22:22:37,853 - INFO - Директория уже существует: ./image_temp
2025-03-02 22:22:37,853 - INFO - Директория уже существует: ./output_video
2025-03-02 22:22:37,854 - INFO - Директория уже существует: ./output_preview
2025-03-02 22:22:37,854 - INFO - Директория уже существует: ./user_logo
2025-03-02 22:22:37,859 - INFO - Задача fetch_and_cache_profiles добавлена в расписание (каждые 5 минут).
2025-03-02 22:22:37,859 - INFO - Задача sync_data_to_db добавлена в расписание (каждые 8 минут).
2025-03-02 22:22:37,860 - INFO - Задача очистки временных файлов добавлена в расписание (каждый день в 00:00).
2025-03-02 22:22:37,860 - INFO - Задача очистки логов добавлена в расписание (каждые 5 минут).
2025-03-02 22:22:37,861 - INFO - Планировщик задач успешно запущен.
2025-03-02 22:27:03,320 - INFO - Запуск подписки на канал Redis для получения задач
2025-03-02 22:27:03,331 - INFO - Redis доступен.
2025-03-02 22:27:03,331 - INFO - Подключаемся к Redis...
2025-03-02 22:27:03,333 - INFO - Подписались на канал video_tasks
2025-03-02 22:27:03,370 - INFO - Запуск приложения и инициализация базы данных...
2025-03-02 22:27:03,370 - DEBUG - Начало инициализации базы данных...
2025-03-02 22:27:03,458 - INFO - База данных успешно инициализирована.
2025-03-02 22:27:03,460 - INFO - Приложение успешно запущено. Соединение с базой данных установлено.
2025-03-02 22:27:03,462 - INFO - Директория уже существует: ./video_temp
2025-03-02 22:27:03,462 - INFO - Директория уже существует: ./image_temp
2025-03-02 22:27:03,462 - INFO - Директория уже существует: ./output_video
2025-03-02 22:27:03,462 - INFO - Директория уже существует: ./output_preview
2025-03-02 22:27:03,463 - INFO - Директория уже существует: ./user_logo
2025-03-02 22:27:03,466 - INFO - Задача fetch_and_cache_profiles добавлена в расписание (каждые 5 минут).
2025-03-02 22:27:03,466 - INFO - Задача sync_data_to_db добавлена в расписание (каждые 8 минут).
2025-03-02 22:27:03,466 - INFO - Задача очистки временных файлов добавлена в расписание (каждый день в 00:00).
2025-03-02 22:27:03,467 - INFO - Задача очистки логов добавлена в расписание (каждые 5 минут).
2025-03-02 22:27:03,467 - INFO - Планировщик задач успешно запущен.
2025-03-02 22:27:32,957 - INFO - Открытие сессии с БД...
2025-03-02 22:27:32,966 - INFO - Сессия с БД успешно открыта.
2025-03-02 22:27:32,997 - INFO - Начало хеширования номера кошелька.
2025-03-02 22:27:32,998 - INFO - Хеш номера кошелька: 3b328e180a43d697ac9213d478521888c6d26383973afe6d83e1db60da7aaf47
2025-03-02 22:27:32,998 - INFO - Поиск пользователя в базе данных.
2025-03-02 22:27:33,084 - INFO - Пользователь не найден, создаем нового.
2025-03-02 22:27:33,114 - INFO - Создан новый пользователь с ID 936
2025-03-02 22:27:33,115 - INFO - Генерация токенов для пользователя.
2025-03-02 22:27:33,116 - INFO - Токены успешно сгенерированы.
2025-03-02 22:27:33,117 - INFO - Закрытие сессии с БД.
2025-03-02 22:28:09,648 - INFO - Получен запрос на загрузку изображения от пользователя с ID: 936
2025-03-02 22:28:09,663 - INFO - Изображение сохранено во временной директории: ./image_temp/9e3cc060-1821-46de-acf0-23c7472e36ac_orig_cat.webp (Размер: 0.07 MB)
2025-03-02 22:28:09,663 - INFO - Изображение успешно загружено: ./image_temp/9e3cc060-1821-46de-acf0-23c7472e36ac_orig_cat.webp
2025-03-02 22:29:13,336 - INFO - Получены данные профиля: {'name': 'Гавноед', 'website_or_social': 'https://twitter.com/johndoe', 'activity_hobbies': 'Gaming, Traveling', 'hashtags': ['Жрать гавно'], 'adress': ['123 Example Street, Example City', '456 Another Street, Another City'], 'city': 'Поппенгагген', 'coordinates': [(59.77, 37.68)], 'is_in_mlm': 1, 'is_incognito': False, 'wallet_number': '0x95b9B8cfa39fA73f48Ad574F600D86EBC2d4753', 'language': None}
2025-03-02 22:29:13,337 - INFO - Получены данные о изображении: {'image_path': './image_temp/9e3cc060-1821-46de-acf0-23c7472e36ac_orig_cat.webp'}
2025-03-02 22:29:13,374 - INFO - Путь к изображению: ./image_temp/9e3cc060-1821-46de-acf0-23c7472e36ac_orig_cat.webp
2025-03-02 22:29:13,375 - INFO - Абсолютный путь к изображению: /app/image_temp/9e3cc060-1821-46de-acf0-23c7472e36ac_orig_cat.webp
2025-03-02 22:29:13,386 - INFO - Изображение перемещено в директорию user_logo: ./user_logo/25c215a8-7e81-4532-9b41-2c8a777d70c4_9e3cc060-1821-46de-acf0-23c7472e36ac_orig_cat.webp (Размер: 0.07 MB)
2025-03-02 22:29:13,386 - INFO - Путь к файлу для сохранения в БД: ./user_logo/25c215a8-7e81-4532-9b41-2c8a777d70c4_9e3cc060-1821-46de-acf0-23c7472e36ac_orig_cat.webp
2025-03-02 22:29:13,386 - INFO - Изображение успешно перемещено в постоянную папку: ./user_logo/25c215a8-7e81-4532-9b41-2c8a777d70c4_9e3cc060-1821-46de-acf0-23c7472e36ac_orig_cat.webp
2025-03-02 22:29:13,388 - INFO - Открытие сессии с БД...
2025-03-02 22:29:13,395 - INFO - Сессия с БД успешно открыта.
2025-03-02 22:29:13,656 - INFO - Создан профиль для пользователя 936, флаг is_profile_created установлен в True
2025-03-02 22:29:13,660 - INFO - Хэштеги добавлены/обновлены для профиля пользователя 936
2025-03-02 22:29:13,669 - INFO - Профиль успешно сохранен.
2025-03-02 22:29:13,669 - INFO - Закрытие сессии с БД.
2025-03-02 22:30:58,866 - ERROR - Ошибка при получении сообщения: Connection closed by server.
Module: __main__, Function: main, Line: 149
